### ISSUE TITLE
Allow for XML void tag syntax

### ISSUE THREAD

**Issue by ElnuDev** [lambda-fairy/maud#388] opened 2023-08-14 03:29 UTC
Hello! I am aware that what I'm asking for is a little bit outside of the scope of maud (SVG templates, rather than HTML templates) but I'm wondering, would it be possible to have an option for properly closing void tags? For instance, somehow having an option/alternate syntax such that `br;` outputs `<br />` rather than `<br>`. This is required for SVG and XML more broadly, and I do know there are some people who want their HTML to be XML-compliant like this, so I think it's worth considering.

This could potentially be behind a feature flag. If you're open to the idea, I'd be happy to make a pull request.

Thanks!

**Comment by lambda-fairy** [comment] 2023-08-27 04:29
Hi @ElnuDev, I believe #62 is a duplicate of this. So I will close in favor of that issue. Thanks!

**Closed by lambda-fairy** 2023-08-27 04:29 UTC

**Comment by ElnuDev** [comment] 2023-08-27 15:59
Alright, thanks! Somehow I didn't notice that issue.
